### ISSUE TITLE
"TypeError: this._allowedOrigins.isWhitelisted is not a function" on startup

### ISSUE THREAD

**Issue by njlie** [interledgerjs/moneyd-xrp#13]
```
set environment; starting moneyd
2018-02-13T18:15:39.016Z connector:accounts info add account. accountId=parent
2018-02-13T18:15:39.349Z connector:accounts warn DEPRECATED: plugin accessed deprecated _log property. accountId=parent
2018-02-13T18:15:39.350Z connector:accounts info add account. accountId=local
2018-02-13T18:15:39.352Z connector:accounts warn DEPRECATED: plugin accessed deprecated _log property. accountId=local
2018-02-13T18:15:39.353Z connector:accounts warn DEPRECATED: plugin accessed deprecated _store property. accountId=local
2018-02-13T18:15:39.353Z connector:accounts warn DEPRECATED: plugin accessed deprecated _store property. accountId=local
2018-02-13T18:15:41.268Z connector:accounts info setting ilp address. oldAddress=unknown newAddress=g.scylla.client.vvRBd6yVIqTvW-QBaLEGI7-dXrXhnpUiREstHZzgIjs
2018-02-13T18:15:41.278Z connector:app info connector ready (republic attitude). address=g.scylla.client.vvRBd6yVIqTvW-QBaLEGI7-dXrXhnpUiREstHZzgIjs

/usr/local/lib/node_modules/moneyd/node_modules/ilp-plugin-mini-accounts/index.js:60`
      if (req.headers && req.headers.origin && !this._allowedOrigins.isWhitelisted(req.headers.origin)) {
                                                                     ^
TypeError: this._allowedOrigins.isWhitelisted is not a function
    at WebSocketServer.wss.on (/usr/local/lib/node_modules/moneyd/node_modules/ilp-plugin-mini-accounts/index.js:60:70)
    at emitTwo (events.js:126:13)
    at WebSocketServer.emit (events.js:214:7)
    at handleUpgrade (/usr/local/lib/node_modules/moneyd/node_modules/ws/lib/WebSocketServer.js:87:16)
    at WebSocketServer.completeUpgrade (/usr/local/lib/node_modules/moneyd/node_modules/ws/lib/WebSocketServer.js:288:5)
    at WebSocketServer.handleUpgrade (/usr/local/lib/node_modules/moneyd/node_modules/ws/lib/WebSocketServer.js:227:10)
    at Server.WebSocketServer._ultron.on (/usr/local/lib/node_modules/moneyd/node_modules/ws/lib/WebSocketServer.js:86:14)
    at emitThree (events.js:136:13)
    at Server.emit (events.js:217:7)
    at onParserExecuteCommon (_http_server.js:495:14)
```
Occurs upon executing `moneyd start`, after connector is readied.

**Comment by sharafian** [comment]
fixed in 3.3.1
