### ISSUE TITLE
Balance middleware error - attempting to settle a 0 amount

### ISSUE THREAD

**Issue by emschwartz** [interledgerjs/moneyd-xrp#22]
Just installed a fresh moneyd instance and connected to the testnet. A couple seconds later it logged this error:

```sh
2018-03-20T15:38:12.261Z connector:balance-middleware error error occurred during settlement. accountId=parent settleAmount=10000 errInfo=Error: amount is not a valid xrp amount. amount=0
    at Object.encodeClaim (/usr/local/lib/node_modules/moneyd/node_modules/ilp-plugin-xrp-paychan-shared/lib/util.js:73:11)
    at Plugin.sendMoney (/usr/local/lib/node_modules/moneyd/node_modules/ilp-plugin-xrp-asym-client/index.js:366:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

This sounds like something related to XRP amount rounding

**Comment by sharafian** [comment]
Looks like the amount validation that I added to paychan shared caused zero amounts to no longer be permitted. When there hasn't been a previous claim, the lastClaim would be zero, and encoding it would throw an error. I'll submit a fix
